# Generated by Django 4.2.12 on 2024-05-17 10:48

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=django_summernote.fields.SummernoteTextField(
                blank=True, max_length=2500, null=True
            ),
        ),
    ]
