# Generated by Django 4.2.12 on 2024-05-19 20:05

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=djrichtextfield.models.RichTextField(
                blank=True, max_length=2500, null=True
            ),
        ),
    ]
