# Generated by Django 5.0.6 on 2024-05-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_liked_posts_alter_profile_bio_postlike"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PostLike",
        ),
    ]
