# Generated by Django 5.0.6 on 2024-05-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_comment"),
        ("profiles", "0004_profile_liked_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="liked_post",
            field=models.ManyToManyField(
                blank=True, related_name="liked_post", to="blog.post"
            ),
        ),
    ]
