# Generated by Django 5.0.6 on 2024-06-06 16:56

import djrichtextfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_postlike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=djrichtextfield.models.RichTextField(max_length=10000),
        ),
    ]
