# Generated by Django 5.0.6 on 2024-05-21 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_likes_postlike"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PostLike",
        ),
    ]
